name: test-coverage CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: test & publish coverage
        uses: actions/setup-node@v2
        env: 
          CC_TEST_REPORTER_ID: a9cbc2c520b684403d5cead73323d6763deb85b1e2494a6f2999c24352430c42
        with:
          coverageCommand: make test-coverage
          debug: true
